/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.33. DO NOT EDIT.

package v1alpha1

import (
	syncagentv1alpha1 "github.com/kcp-dev/api-syncagent/sdk/apis/syncagent/v1alpha1"
)

// RelatedResourceSpecApplyConfiguration represents a declarative configuration of the RelatedResourceSpec type for use
// with apply.
type RelatedResourceSpecApplyConfiguration struct {
	Identifier    *string                                         `json:"identifier,omitempty"`
	Origin        *syncagentv1alpha1.RelatedResourceOrigin        `json:"origin,omitempty"`
	Group         *string                                         `json:"group,omitempty"`
	Version       *string                                         `json:"version,omitempty"`
	Resource      *string                                         `json:"resource,omitempty"`
	Kind          *string                                         `json:"kind,omitempty"`
	IdentityHash  *string                                         `json:"identityHash,omitempty"`
	Cleanup       *bool                                           `json:"cleanup,omitempty"`
	CleanupPolicy *syncagentv1alpha1.RelatedResourceCleanupPolicy `json:"cleanupPolicy,omitempty"`
	Projection    *RelatedResourceProjectionApplyConfiguration    `json:"projection,omitempty"`
	Object        *RelatedResourceObjectApplyConfiguration        `json:"object,omitempty"`
	Mutation      *ResourceMutationSpecApplyConfiguration         `json:"mutation,omitempty"`
	Watch         *RelatedResourceWatchApplyConfiguration         `json:"watch,omitempty"`
	SyncStatus    *bool                                           `json:"syncStatus,omitempty"`
}

// RelatedResourceSpecApplyConfiguration constructs a declarative configuration of the RelatedResourceSpec type for use with
// apply.
func RelatedResourceSpec() *RelatedResourceSpecApplyConfiguration {
	return &RelatedResourceSpecApplyConfiguration{}
}

// WithIdentifier sets the Identifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identifier field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithIdentifier(value string) *RelatedResourceSpecApplyConfiguration {
	b.Identifier = &value
	return b
}

// WithOrigin sets the Origin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Origin field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithOrigin(value syncagentv1alpha1.RelatedResourceOrigin) *RelatedResourceSpecApplyConfiguration {
	b.Origin = &value
	return b
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithGroup(value string) *RelatedResourceSpecApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithVersion(value string) *RelatedResourceSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithResource(value string) *RelatedResourceSpecApplyConfiguration {
	b.Resource = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithKind(value string) *RelatedResourceSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithIdentityHash sets the IdentityHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentityHash field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithIdentityHash(value string) *RelatedResourceSpecApplyConfiguration {
	b.IdentityHash = &value
	return b
}

// WithCleanup sets the Cleanup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cleanup field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithCleanup(value bool) *RelatedResourceSpecApplyConfiguration {
	b.Cleanup = &value
	return b
}

// WithCleanupPolicy sets the CleanupPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CleanupPolicy field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithCleanupPolicy(value syncagentv1alpha1.RelatedResourceCleanupPolicy) *RelatedResourceSpecApplyConfiguration {
	b.CleanupPolicy = &value
	return b
}

// WithProjection sets the Projection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Projection field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithProjection(value *RelatedResourceProjectionApplyConfiguration) *RelatedResourceSpecApplyConfiguration {
	b.Projection = value
	return b
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithObject(value *RelatedResourceObjectApplyConfiguration) *RelatedResourceSpecApplyConfiguration {
	b.Object = value
	return b
}

// WithMutation sets the Mutation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mutation field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithMutation(value *ResourceMutationSpecApplyConfiguration) *RelatedResourceSpecApplyConfiguration {
	b.Mutation = value
	return b
}

// WithWatch sets the Watch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Watch field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithWatch(value *RelatedResourceWatchApplyConfiguration) *RelatedResourceSpecApplyConfiguration {
	b.Watch = value
	return b
}

// WithSyncStatus sets the SyncStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SyncStatus field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithSyncStatus(value bool) *RelatedResourceSpecApplyConfiguration {
	b.SyncStatus = &value
	return b
}
